//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BillingSystem
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbRaffleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbRaffleEntities object using the connection string found in the 'dbRaffleEntities' section of the application configuration file.
        /// </summary>
        public dbRaffleEntities() : base("name=dbRaffleEntities", "dbRaffleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbRaffleEntities object.
        /// </summary>
        public dbRaffleEntities(string connectionString) : base(connectionString, "dbRaffleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbRaffleEntities object.
        /// </summary>
        public dbRaffleEntities(EntityConnection connection) : base(connection, "dbRaffleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbRaffeEntry> tbRaffeEntries
        {
            get
            {
                if ((_tbRaffeEntries == null))
                {
                    _tbRaffeEntries = base.CreateObjectSet<tbRaffeEntry>("tbRaffeEntries");
                }
                return _tbRaffeEntries;
            }
        }
        private ObjectSet<tbRaffeEntry> _tbRaffeEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbRafflePeriod> tbRafflePeriods
        {
            get
            {
                if ((_tbRafflePeriods == null))
                {
                    _tbRafflePeriods = base.CreateObjectSet<tbRafflePeriod>("tbRafflePeriods");
                }
                return _tbRafflePeriods;
            }
        }
        private ObjectSet<tbRafflePeriod> _tbRafflePeriods;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbRaffeEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbRaffeEntries(tbRaffeEntry tbRaffeEntry)
        {
            base.AddObject("tbRaffeEntries", tbRaffeEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbRafflePeriods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbRafflePeriods(tbRafflePeriod tbRafflePeriod)
        {
            base.AddObject("tbRafflePeriods", tbRafflePeriod);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbRaffleModel", Name="tbRaffeEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbRaffeEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbRaffeEntry object.
        /// </summary>
        /// <param name="entry_id">Initial value of the entry_id property.</param>
        public static tbRaffeEntry CreatetbRaffeEntry(global::System.Int32 entry_id)
        {
            tbRaffeEntry tbRaffeEntry = new tbRaffeEntry();
            tbRaffeEntry.entry_id = entry_id;
            return tbRaffeEntry;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 entry_id
        {
            get
            {
                return _entry_id;
            }
            set
            {
                if (_entry_id != value)
                {
                    Onentry_idChanging(value);
                    ReportPropertyChanging("entry_id");
                    _entry_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("entry_id");
                    Onentry_idChanged();
                }
            }
        }
        private global::System.Int32 _entry_id;
        partial void Onentry_idChanging(global::System.Int32 value);
        partial void Onentry_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> raffle_id
        {
            get
            {
                return _raffle_id;
            }
            set
            {
                Onraffle_idChanging(value);
                ReportPropertyChanging("raffle_id");
                _raffle_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("raffle_id");
                Onraffle_idChanged();
            }
        }
        private Nullable<global::System.Int32> _raffle_id;
        partial void Onraffle_idChanging(Nullable<global::System.Int32> value);
        partial void Onraffle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acctno
        {
            get
            {
                return _acctno;
            }
            set
            {
                OnacctnoChanging(value);
                ReportPropertyChanging("acctno");
                _acctno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acctno");
                OnacctnoChanged();
            }
        }
        private global::System.String _acctno;
        partial void OnacctnoChanging(global::System.String value);
        partial void OnacctnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acctname
        {
            get
            {
                return _acctname;
            }
            set
            {
                OnacctnameChanging(value);
                ReportPropertyChanging("acctname");
                _acctname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acctname");
                OnacctnameChanged();
            }
        }
        private global::System.String _acctname;
        partial void OnacctnameChanging(global::System.String value);
        partial void OnacctnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> added_date
        {
            get
            {
                return _added_date;
            }
            set
            {
                Onadded_dateChanging(value);
                ReportPropertyChanging("added_date");
                _added_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("added_date");
                Onadded_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _added_date;
        partial void Onadded_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onadded_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String added_by
        {
            get
            {
                return _added_by;
            }
            set
            {
                Onadded_byChanging(value);
                ReportPropertyChanging("added_by");
                _added_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("added_by");
                Onadded_byChanged();
            }
        }
        private global::System.String _added_by;
        partial void Onadded_byChanging(global::System.String value);
        partial void Onadded_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> master_id
        {
            get
            {
                return _master_id;
            }
            set
            {
                Onmaster_idChanging(value);
                ReportPropertyChanging("master_id");
                _master_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("master_id");
                Onmaster_idChanged();
            }
        }
        private Nullable<global::System.Int32> _master_id;
        partial void Onmaster_idChanging(Nullable<global::System.Int32> value);
        partial void Onmaster_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remarks
        {
            get
            {
                return _remarks;
            }
            set
            {
                OnremarksChanging(value);
                ReportPropertyChanging("remarks");
                _remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remarks");
                OnremarksChanged();
            }
        }
        private global::System.String _remarks;
        partial void OnremarksChanging(global::System.String value);
        partial void OnremarksChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbRaffleModel", Name="tbRafflePeriod")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbRafflePeriod : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbRafflePeriod object.
        /// </summary>
        /// <param name="raffle_id">Initial value of the raffle_id property.</param>
        /// <param name="raffle_description">Initial value of the raffle_description property.</param>
        public static tbRafflePeriod CreatetbRafflePeriod(global::System.Int32 raffle_id, global::System.String raffle_description)
        {
            tbRafflePeriod tbRafflePeriod = new tbRafflePeriod();
            tbRafflePeriod.raffle_id = raffle_id;
            tbRafflePeriod.raffle_description = raffle_description;
            return tbRafflePeriod;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 raffle_id
        {
            get
            {
                return _raffle_id;
            }
            set
            {
                if (_raffle_id != value)
                {
                    Onraffle_idChanging(value);
                    ReportPropertyChanging("raffle_id");
                    _raffle_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("raffle_id");
                    Onraffle_idChanged();
                }
            }
        }
        private global::System.Int32 _raffle_id;
        partial void Onraffle_idChanging(global::System.Int32 value);
        partial void Onraffle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String raffle_description
        {
            get
            {
                return _raffle_description;
            }
            set
            {
                Onraffle_descriptionChanging(value);
                ReportPropertyChanging("raffle_description");
                _raffle_description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("raffle_description");
                Onraffle_descriptionChanged();
            }
        }
        private global::System.String _raffle_description;
        partial void Onraffle_descriptionChanging(global::System.String value);
        partial void Onraffle_descriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String raffle_period
        {
            get
            {
                return _raffle_period;
            }
            set
            {
                Onraffle_periodChanging(value);
                ReportPropertyChanging("raffle_period");
                _raffle_period = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("raffle_period");
                Onraffle_periodChanged();
            }
        }
        private global::System.String _raffle_period;
        partial void Onraffle_periodChanging(global::System.String value);
        partial void Onraffle_periodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remarks
        {
            get
            {
                return _remarks;
            }
            set
            {
                OnremarksChanging(value);
                ReportPropertyChanging("remarks");
                _remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remarks");
                OnremarksChanged();
            }
        }
        private global::System.String _remarks;
        partial void OnremarksChanging(global::System.String value);
        partial void OnremarksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> added_date
        {
            get
            {
                return _added_date;
            }
            set
            {
                Onadded_dateChanging(value);
                ReportPropertyChanging("added_date");
                _added_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("added_date");
                Onadded_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _added_date;
        partial void Onadded_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onadded_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String added_by
        {
            get
            {
                return _added_by;
            }
            set
            {
                Onadded_byChanging(value);
                ReportPropertyChanging("added_by");
                _added_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("added_by");
                Onadded_byChanged();
            }
        }
        private global::System.String _added_by;
        partial void Onadded_byChanging(global::System.String value);
        partial void Onadded_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> draw_date
        {
            get
            {
                return _draw_date;
            }
            set
            {
                Ondraw_dateChanging(value);
                ReportPropertyChanging("draw_date");
                _draw_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("draw_date");
                Ondraw_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _draw_date;
        partial void Ondraw_dateChanging(Nullable<global::System.DateTime> value);
        partial void Ondraw_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qualified_entries
        {
            get
            {
                return _qualified_entries;
            }
            set
            {
                Onqualified_entriesChanging(value);
                ReportPropertyChanging("qualified_entries");
                _qualified_entries = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qualified_entries");
                Onqualified_entriesChanged();
            }
        }
        private Nullable<global::System.Int32> _qualified_entries;
        partial void Onqualified_entriesChanging(Nullable<global::System.Int32> value);
        partial void Onqualified_entriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> generated_date
        {
            get
            {
                return _generated_date;
            }
            set
            {
                Ongenerated_dateChanging(value);
                ReportPropertyChanging("generated_date");
                _generated_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("generated_date");
                Ongenerated_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _generated_date;
        partial void Ongenerated_dateChanging(Nullable<global::System.DateTime> value);
        partial void Ongenerated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> cutoff_date
        {
            get
            {
                return _cutoff_date;
            }
            set
            {
                Oncutoff_dateChanging(value);
                ReportPropertyChanging("cutoff_date");
                _cutoff_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cutoff_date");
                Oncutoff_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _cutoff_date;
        partial void Oncutoff_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncutoff_dateChanged();

        #endregion

    
    }

    #endregion

    
}
