//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TWD-MISD-GPC\\SQLSERVERDEV;Connection Timeout=0;Initial Catalog=dbComm" +
            "ercial;Persist Security Info=True;User ID=commsys;Password=comm123;MultipleActiv" +
            "eResultSets=True;Application Name=EntityFramework")]
        public string dbCommercialConnectionString {
            get {
                return ((string)(this["dbCommercialConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TWD-MISD-GPC\\SQLSERVERDEV;Initial Catalog=dbRaffle;User ID=commsys;Pa" +
            "ssword=comm123")]
        public string dbRaffleConnectionString {
            get {
                return ((string)(this["dbRaffleConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BILLSERVERNEW\\BILLSERVER;Initial Catalog=dbCommercial;Persist Securit" +
            "y Info=True;User ID=commsys;Password=comm123")]
        public string dbCommercialConnectionString1 {
            get {
                return ((string)(this["dbCommercialConnectionString1"]));
            }
        }
    }
}
